Add new retry and backoff timer feature
silverstripeltd/silverstripe-forager pull request #11
Opened 2024-12-15 19:10 UTC by chrispenny

Split out from #9 so that this feature can be merge while I still work through the implementation for batch size by class.

2025-01-21 01:12 UTC, blueo requested changes
LGTM just a suggestion around the timing in the test

2025-01-21 01:12 UTC, blueo commented on tests/Extensions/JobRetryExtensionTest.php
> +        $expectedLow = DBDatetime::now()->getTimestamp() + 115;
would setting a mock 'now' help this?

2025-01-21 01:12 UTC, blueo commented on tests/Extensions/JobRetryExtensionTest.php
> +    public function testRetryCodes(int $code): void
does this test need `Config::modify()->set(QueuedJobService::class, 'use_shutdown_function', false);`?

2025-01-21 18:40 UTC, chrispenny commented on tests/Extensions/JobRetryExtensionTest.php
> +        $expectedLow = DBDatetime::now()->getTimestamp() + 115;
I still can't guarantee that the process completes within that same second though, so I think a small buffer is going to be required.

EG:

- I set mock now to `2020-01-01 01:00:00`
- So, I'll be expected a new start time of 2 minutes after this for the first failure (`2020-01-01 01:02:00`)
- The job starts processing
- The job takes > 1s to fail
- The job sets the new start time as `2020-01-01 01:02:01`
- Test fails

I could move things around a bit so that the buffer is smaller, but I'm not sure it can be completely avoided, since I can't know the exact second when the job process fails and sets the new start time.

2025-01-21 18:50 UTC, chrispenny commented on tests/Extensions/JobRetryExtensionTest.php
> +    public function testRetryCodes(int $code): void
Ah yea, that old chestnut. I haven't seen any issues yet, but I'll add it now anyway.

2025-01-22 00:32 UTC, blueo commented on tests/Extensions/JobRetryExtensionTest.php
> +        $expectedLow = DBDatetime::now()->getTimestamp() + 115;
ah I see yeah you could end up with fairly useless test failures just as you add logic etc - all good

2025-01-22 01:09 UTC, merged